- name: Push container images to ARC registry
  hosts: localhost
  become: true
  vars:
    acr_name: "casopractico2acrcristina.azurecr.io"
    acr_username: "casopractico2acrcristina"
    acr_password: "{{ acr_password }}"
  tasks:
    - name: Ensure Podman is installed
      ansible.builtin.apt:
        name: podman
        update_cache: yes
        state: present
    
    - name: Login to ARC
      containers.podman.podman_login:
        registry: "{{ acr_name }}"
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"
    
    - name: Pull Nginx image
      containers.podman.podman_image:
        name: "docker.io/nginx"
    - name: Pull Redis image
      containers.podman.podman_image:
        name: "mcr.microsoft.com/oss/bitnami/redis"
        tag: "6.0.8"
    # - name: Pull Azure vote Front image
    #   containers.podman.podman_image:
    #     name: "mcr.microsoft.com/azuredocs/azure-vote-front"
    #     tag: "v1"
    
    - name: Tag Nginx image for ACR
      command: podman tag docker.io/nginx:latest {{ acr_name }}/nginx/nginx:casopractico2
    - name: Tag Redis image for ACR
      command: podman tag mcr.microsoft.com/oss/bitnami/redis:6.0.8 {{ acr_name }}/redis/redis:casopractico2
    
    - name: Push Nginx image to ACR
      containers.podman.podman_image:
        name: "{{ acr_name }}/nginx/nginx"
        tag: "casopractico2"
        push: yes
    - name: Push Redis image to ACR
      containers.podman.podman_image:
        name: "{{ acr_name }}/redis/redis"
        tag: "casopractico2"
        push: yes
    # - name: Push Azure vote Front image to ACR
    #   containers.podman.podman_image:
    #     name: "{{ acr_name }}/front/azure-vote-front"
    #     tag: "casopractico2"
    #     push: yes
