FROM python:3.10-slim

WORKDIR /app

# Copy app
COPY . /app

# Install Python dependencies
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Expose 5000 port
EXPOSE 5000

# Configure env vars
ENV REDIS_HOST=redis
ENV REDIS_PORT=6379

# Start app
CMD ["python", "app.py"]
